username = None
account_balance = None
user_id = None
email = None
password = None
payment_method = 'credit card'
card_number = '2330138121'
role = None
products = None
product_quantity = None
total_price = None
total_purchases = None
total_amount_spent = None
most_visited_mall= None
most_bought_product = None
total_items_bought = None
most_recent_purchase_product = None
most_recent_purchase_product_quantity = None
most_recent_purchase_product_amount = None
most_active_day_of_the_week = None
