# Form implementation generated from reading ui file 'e-mall-main-win.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import time

import config
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QTimer
from utilities import *


class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()
        self.main_app_ui = None
        self.initial_main_window = None
        self.main_app_window = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 601)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_bg_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.main_bg_frame.setGeometry(QtCore.QRect(50, 0, 811, 611))
        self.main_bg_frame.setStyleSheet("background-color: white;\n"
                                         "")
        self.main_bg_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_bg_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_bg_frame.setObjectName("main_bg_frame")
        self.login_frame = QtWidgets.QFrame(parent=self.main_bg_frame)
        self.login_frame.setGeometry(QtCore.QRect(350, 30, 301, 521))
        self.login_frame.setStyleSheet("background: none;\n"
                                       "border: 5px solid blue;\n"
                                       "border-left-color: none;\n"
                                       "border-radius: 200px")
        self.login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.login_frame.setObjectName("login_frame")
        self.sign_in_page = QtWidgets.QStackedWidget(parent=self.login_frame)
        self.sign_in_page.setGeometry(QtCore.QRect(-10, 50, 301, 411))
        self.sign_in_page.setStyleSheet("background: none;\n"
                                        "border: none;")
        self.sign_in_page.setObjectName("sign_in_page")
        self.sign_in_pae = QtWidgets.QWidget()
        self.sign_in_pae.setObjectName("sign_in_pae")
        self.sign_in_frame = QtWidgets.QFrame(parent=self.sign_in_pae)
        self.sign_in_frame.setGeometry(QtCore.QRect(10, 0, 291, 381))
        self.sign_in_frame.setStyleSheet("background-color: none;\n"
                                         "border: none")
        self.sign_in_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sign_in_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sign_in_frame.setObjectName("sign_in_frame")
        self.password_edit = QtWidgets.QLineEdit(parent=self.sign_in_frame)
        self.password_edit.setGeometry(QtCore.QRect(20, 160, 261, 31))
        self.password_edit.setStyleSheet("font: 8pt \"CentSchbkCyrill BT\";\n"
                                         "text-decoration: none;\n"
                                         "border: 5px solid;\n"
                                         "border-bottom-color: blue")
        self.password_edit.setText("")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_edit.setClearButtonEnabled(True)
        self.password_edit.setObjectName("password_edit")
        self.user_name_email_line = QtWidgets.QLineEdit(parent=self.sign_in_frame)
        self.user_name_email_line.setGeometry(QtCore.QRect(20, 100, 261, 31))
        self.user_name_email_line.setStyleSheet("font: 8pt \"CentSchbkCyrill BT\";\n"
                                                "text-decoration: none;\n"
                                                "border: 5px solid;\n"
                                                "border-bottom-color: blue")
        self.user_name_email_line.setText("")
        self.user_name_email_line.setClearButtonEnabled(True)
        self.user_name_email_line.setObjectName("user_name_email_line")
        self.sign_in_label_2 = QtWidgets.QLabel(parent=self.sign_in_frame)
        self.sign_in_label_2.setGeometry(QtCore.QRect(70, 20, 141, 61))
        self.sign_in_label_2.setStyleSheet("font: 28pt \"CentSchbkCyrill BT\";")
        self.sign_in_label_2.setObjectName("sign_in_label_2")
        self.continue_button = QtWidgets.QPushButton(parent=self.sign_in_frame)
        self.continue_button.setGeometry(QtCore.QRect(50, 220, 201, 21))
        self.continue_button.setStyleSheet("QPushButton {\n"
                                           "                background-color: blue;\n"
                                           "                border: none;\n"
                                           "                border-radius: 5px;\n"
                                           "            }\n"
                                           "QPushButton:hover {\n"
                                           "                background-color: #8f8f8f;\n"
                                           "            }")
        self.continue_button.setObjectName("continue_button")
        self.continue_button.clicked.connect(self.handle_login)
        self.label = QtWidgets.QLabel(parent=self.sign_in_frame)
        self.label.setGeometry(QtCore.QRect(100, 260, 91, 31))
        self.label.setObjectName("label")
        self.continue_button_3 = QtWidgets.QPushButton(parent=self.sign_in_pae)
        self.continue_button_3.setGeometry(QtCore.QRect(50, 310, 221, 51))
        self.continue_button_3.setStyleSheet("QPushButton {\n"
                                             "                background-color: blue;\n"
                                             "                border: none;\n"
                                             "                border-radius: 5px;\n"
                                             "            }\n"
                                             "QPushButton:hover {\n"
                                             "                background-color: #8f8f8f;\n"
                                             "            };\n"
                                             "")
        self.continue_button_3.setObjectName("continue_button_3")
        self.continue_button_3.clicked.connect(self.enter_sign_up)
        self.sign_in_page.addWidget(self.sign_in_pae)
        self.sign_up_page = QtWidgets.QWidget()
        self.sign_up_page.setObjectName("sign_up_page")
        self.sign_in_frame_2 = QtWidgets.QFrame(parent=self.sign_up_page)
        self.sign_in_frame_2.setGeometry(QtCore.QRect(10, 30, 291, 321))
        self.sign_in_frame_2.setStyleSheet("background-color: none;\n"
                                           "border: none")
        self.sign_in_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sign_in_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sign_in_frame_2.setObjectName("sign_in_frame_2")
        self.password_edit_2 = QtWidgets.QLineEdit(parent=self.sign_in_frame_2)
        self.password_edit_2.setGeometry(QtCore.QRect(20, 200, 261, 31))
        self.password_edit_2.setStyleSheet("font: 8pt \"CentSchbkCyrill BT\";\n"
                                           "text-decoration: none;\n"
                                           "border: 5px solid;\n"
                                           "border-bottom-color: blue")
        self.password_edit_2.setText("")
        self.password_edit_2.setClearButtonEnabled(True)
        self.password_edit_2.setObjectName("password_edit_2")
        self.user_name_email_line_2 = QtWidgets.QLineEdit(parent=self.sign_in_frame_2)
        self.user_name_email_line_2.setGeometry(QtCore.QRect(20, 100, 261, 31))
        self.user_name_email_line_2.setStyleSheet("font: 8pt \"CentSchbkCyrill BT\";\n"
                                                  "text-decoration: none;\n"
                                                  "border: 5px solid;\n"
                                                  "border-bottom-color: blue")
        self.user_name_email_line_2.setText("")
        self.user_name_email_line_2.setClearButtonEnabled(True)
        self.user_name_email_line_2.setObjectName("user_name_email_line_2")
        self.sign_in_label_3 = QtWidgets.QLabel(parent=self.sign_in_frame_2)
        self.sign_in_label_3.setGeometry(QtCore.QRect(70, 20, 151, 61))
        self.sign_in_label_3.setStyleSheet("font: 28pt \"CentSchbkCyrill BT\";")
        self.sign_in_label_3.setObjectName("sign_in_label_3")
        self.submit_button = QtWidgets.QPushButton(parent=self.sign_in_frame_2)
        self.submit_button.setGeometry(QtCore.QRect(50, 270, 201, 21))
        self.submit_button.setStyleSheet("QPushButton {\n"
                                         "                background-color: blue;\n"
                                         "                border: none;\n"
                                         "                border-radius: 5px;\n"
                                         "            }\n"
                                         "QPushButton:hover {\n"
                                         "                background-color: #8f8f8f;\n"
                                         "            }")
        self.submit_button.setObjectName("submit_button")
        self.submit_button.clicked.connect(self.handle_sign_up)
        self.user_name_email_line_3 = QtWidgets.QLineEdit(parent=self.sign_in_frame_2)
        self.user_name_email_line_3.setGeometry(QtCore.QRect(20, 150, 261, 31))
        self.user_name_email_line_3.setStyleSheet("font: 8pt \"CentSchbkCyrill BT\";\n"
                                                  "text-decoration: none;\n"
                                                  "border: 5px solid;\n"
                                                  "border-bottom-color: blue")
        self.user_name_email_line_3.setText("")
        self.user_name_email_line_3.setClearButtonEnabled(True)
        self.user_name_email_line_3.setObjectName("user_name_email_line_3")
        self.sign_in_page.addWidget(self.sign_up_page)
        self.color_welcome_frame = QtWidgets.QFrame(parent=self.main_bg_frame)
        self.color_welcome_frame.setGeometry(QtCore.QRect(30, 30, 401, 521))
        self.color_welcome_frame.setStyleSheet("border: 5px solid blue;\n"
                                               "background-color: qlineargradient(spread:pad, x1:0.784, y1:0.920091, x2:0.039, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                               "border-right-color: none;")
        self.color_welcome_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.color_welcome_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.color_welcome_frame.setObjectName("color_welcome_frame")
        self.welcome_frame = QtWidgets.QFrame(parent=self.color_welcome_frame)
        self.welcome_frame.setGeometry(QtCore.QRect(10, 0, 441, 581))
        self.welcome_frame.setStyleSheet("background-color: none;\n"
                                         "border: none")
        self.welcome_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.welcome_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.welcome_frame.setObjectName("welcome_frame")
        self.curved_line_frame = QtWidgets.QFrame(parent=self.welcome_frame)
        self.curved_line_frame.setGeometry(QtCore.QRect(280, 0, 521, 521))
        self.curved_line_frame.setStyleSheet("border-color: rgb(34, 55, 172);\n"
                                             "border: 5px solid rgb(34, 55, 172);\n"
                                             "border-radius: 100px;\n"
                                             "background-color: white;")
        self.curved_line_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.curved_line_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.curved_line_frame.setObjectName("curved_line_frame")
        self.welcome_text_frame = QtWidgets.QFrame(parent=self.welcome_frame)
        self.welcome_text_frame.setGeometry(QtCore.QRect(-10, 140, 291, 111))
        self.welcome_text_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.welcome_text_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.welcome_text_frame.setObjectName("welcome_text_frame")
        self.welcome_label = QtWidgets.QLabel(parent=self.welcome_text_frame)
        self.welcome_label.setGeometry(QtCore.QRect(10, 20, 281, 71))
        self.welcome_label.setStyleSheet("font: 75 24pt \"CentSchbkCyrill BT\";")
        self.welcome_label.setObjectName("welcome_label")
        self.logo_frame = QtWidgets.QFrame(parent=self.welcome_frame)
        self.logo_frame.setGeometry(QtCore.QRect(0, 10, 171, 131))
        self.logo_frame.setStyleSheet("image:url(:images/E-MALL.png)")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.sign_in_text_frame = QtWidgets.QFrame(parent=self.welcome_frame)
        self.sign_in_text_frame.setGeometry(QtCore.QRect(70, 310, 191, 91))
        self.sign_in_text_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sign_in_text_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sign_in_text_frame.setObjectName("sign_in_text_frame")
        self.sign_in_label = QtWidgets.QLabel(parent=self.sign_in_text_frame)
        self.sign_in_label.setGeometry(QtCore.QRect(0, 20, 191, 61))
        self.sign_in_label.setStyleSheet("font: \"CentSchbkCyrill BT\";\n"
                                         "font: 8pt \"Century725 Cn BT\";")
        self.sign_in_label.setObjectName("sign_in_label")
        self.cipher_label = QtWidgets.QLabel(parent=self.welcome_frame)
        self.cipher_label.setGeometry(QtCore.QRect(0, 490, 131, 21))
        self.cipher_label.setObjectName("cipher_label")
        self.color_welcome_frame.raise_()
        self.login_frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.sign_in_page.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # def show_main_app(self):
    #     print('hi')
    #
    #     # Initialize the QApplication (if not already initialized)
    #     if not QtWidgets.QApplication.instance():
    #         app = QtWidgets.QApplication([])
    #
    #     # Create and show the initial main window
    #     self.initial_main_window = MainWindow()
    #     self.initial_main_window.show()
    #
    #     # Connect the close signal to a method to handle the transition
    #     self.initial_main_window.closeEvent = self.on_initial_window_close
    #
    #     # Start the event loop
    #     QtWidgets.QApplication.instance().exec()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cipher E-Mall"))
        self.password_edit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.user_name_email_line.setPlaceholderText(_translate("MainWindow", "Username or Email"))
        self.sign_in_label_2.setText(_translate("MainWindow",
                                                "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">Sign In</span></p></body></html>"))
        self.continue_button.setText(_translate("MainWindow", "Continue"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Or</span></p></body></html>"))
        self.continue_button_3.setText(_translate("MainWindow", "Sign Up"))
        self.password_edit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.user_name_email_line_2.setPlaceholderText(_translate("MainWindow", "Username"))
        self.sign_in_label_3.setText(_translate("MainWindow",
                                                "<html><head/><body><p><span style=\" font-weight:600;\">Sign Up</span></p></body></html>"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.user_name_email_line_3.setPlaceholderText(_translate("MainWindow", "Email"))
        self.welcome_label.setText(_translate("MainWindow",
                                              "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#0000ff;\">WELCOME</span></p></body></html>"))
        self.sign_in_label.setText(_translate("MainWindow",
                                              "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Sign In to</span></p><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Continue Access</span></p></body></html>"))
        self.cipher_label.setText(_translate("MainWindow",
                                             "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Cipher E-Mall</span></p></body></html>"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)  # Set up the UI
        self.continue_button.clicked.connect(self.handle_login)
        self.continue_button_3.clicked.connect(self.enter_sign_up)
        self.submit_button.clicked.connect(self.handle_sign_up)
        self.initial_main_window = self

    def handle_login(self):
        username_or_email = self.user_name_email_line.text()
        password = self.password_edit.text()

        user = login(username_or_email, password)

        if user:
            simulate_loading(f'Welcome {user[1]}!!')
            config.username = user[1]
            config.email = user[2]
            config.password = user[3]
            config.role = user[4]
            config.account_balance = user[5]
            config.user_id = user[0]
            self.clear_inputs()
            self.main_app_window = QtWidgets.QMainWindow()
            self.show_main_app()

        else:
            print('Invalid username or password')

    def enter_sign_up(self):
        self.sign_in_page.setCurrentIndex(1)

    def clear_inputs(self):
        self.user_name_email_line.clear()
        self.password_edit.clear()

    def handle_sign_up(self):
        username = self.user_name_email_line_2.text()
        email = self.user_name_email_line_3.text()
        password = self.password_edit_2.text()

        if not username:
            print("Please enter valid username.")
            return

        if not confirm_user_name(username):
            return

        if not is_valid_email(email):
            print("Please input a valid email.")
            return

        if not confirm_email(email):
            return

        if not is_valid_password(password):
            return

        user_id = generate_user_id()

        user = sign_up(user_id, username, email, password)

        # Check if the user was created successfully
        if user:
            simulate_loading('Account created successfully')
            print(f'Your USER ID: {user_id}')
            self.clear_inputs_1()
            self.sign_in_page.setCurrentIndex(0)
        else:
            print("Failed to create an account.")

    def clear_inputs_1(self):
        self.user_name_email_line_2.clear()
        self.user_name_email_line_3.clear()
        self.password_edit_2.clear()

    def show_main_app(self):
        print('Successful login - opening main app window')

        # Initialize and show the main application window
        from main_app_ui import MainAppUI
        self.main_app_window = QtWidgets.QMainWindow()
        self.main_app_ui = MainAppUI(self.main_app_window)
        self.main_app_ui.setupUi(self.main_app_window)
        self.main_app_window.show()
        self.close_initial_window()

    def close_initial_window(self):
        if self.initial_main_window:
            print('Starting to close initial main window')
            self.initial_main_window.close()
            self.initial_main_window.deleteLater()  # Clean up
            self.initial_main_window = None  # Clear reference
            print('Initial main window closed')


if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    main_window = MainWindow()
    main_window.show()
    app.exec()
