# Form implementation generated from reading ui file 'loadingscreen.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 310)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 411, 311))
        self.frame.setStyleSheet("background-image: url(./images/loadingbg.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(80, 90, 221, 51))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame)
        self.progressBar.setGeometry(QtCore.QRect(90, 220, 221, 21))
        self.progressBar.setStyleSheet("QProgressBar {\n"
                                       "    border: 2px solid #3A3A3A; /* Dark gray border */\n"
                                       "    border-radius: 5px; /* Rounded corners */\n"
                                       "    background-color: #1E1E1E; /* Dark background */\n"
                                       "    text-align: center; /* Centered text */\n"
                                       "    color: white; /* White text color */\n"
                                       "    font-weight: bold; /* Bold text */\n"
                                       "}\n"
                                       "\n"
                                       "QProgressBar::chunk {\n"
                                       "    background-color: #007BFF; /* Blue chunk color */\n"
                                       "    border-radius: 5px; /* Rounded corners for the chunk */\n"
                                       "}\n"
                                       "")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.loading_texts_label = QtWidgets.QLabel(parent=self.frame)
        self.loading_texts_label.setGeometry(QtCore.QRect(90, 190, 231, 16))
        self.loading_texts_label.setStyleSheet("background-color: #1E1E1E; /* Dark background */\n"
                                               "    text-align: center; /* Centered text */\n"
                                               "    color: white; /* White text color */\n"
                                               "    font-weight: bold; /* Bold text */")
        self.loading_texts_label.setObjectName("loading_texts_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#cacaca;\">Cipher E-Mall</span></p></body></html>"))
        self.loading_texts_label.setText(
            _translate("Form", "<html><head/><body><p align=\"center\">Initializing app...</p></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
